### ISSUE TITLE
About Readme

### ISSUE THREAD

**Issue by vignesh-gupta** [RohiniRG/RohiniRG#1]
Hello Rohini, 
I've looked over your profile, couldn't ignore your readme files. Could you please share from where do you create it? I've just reaching out in a new way 😄 

Thanks!

**Comment by vignesh-gupta** [comment]
@RohiniRG would you like to share? OR please feel free to close the issue.

**Comment by RohiniRG** [comment]
@vignesh-gupta Markdown is pretty easy, I created it on my own. Thanks for reaching out
